files:
  - source: /l10n/templates/gpxpod.pot
    translation: /l10n/%locale_with_underscore%/gpxpod.po
  - source: /l10n/descriptions/full_description.md
    translation: /l10n/descriptions/%locale_with_underscore%/full_description.md
  - source: /l10n/descriptions/short_description.txt
    translation: /l10n/descriptions/%locale_with_underscore%/short_description.txt
